/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminFooter: typeof import('./components/backend/AdminFooter.vue')['default']
    AdminSide: typeof import('./components/backend/AdminSide.vue')['default']
    ArticleBox: typeof import('./components/frontend/ArticleBox.vue')['default']
    ArticleInfoSide: typeof import('./components/frontend/Side/ArticleInfoSide.vue')['default']
    ArticleTable: typeof import('./components/backend/Table/ArticleTable.vue')['default']
    Banner: typeof import('./components/frontend/Banner.vue')['default']
    CategoryTable: typeof import('./components/backend/Table/CategoryTable.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    Footer: typeof import('./components/frontend/Footer.vue')['default']
    Header: typeof import('./components/frontend/Header.vue')['default']
    HomeSide: typeof import('./components/frontend/Side/HomeSide.vue')['default']
    Icon: typeof import('./components/Child/Icon.vue')['default']
    Pagination: typeof import('./components/frontend/Pagination.vue')['default']
    Pet: typeof import('./components/frontend/Pet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableDialog: typeof import('./components/backend/Table/TableDialog.vue')['default']
    TagTable: typeof import('./components/backend/Table/TagTable.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
