/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminFooter: typeof import('./src/components/backend/AdminFooter.vue')['default']
    AdminSide: typeof import('./src/components/backend/AdminSide.vue')['default']
    ArticleBox: typeof import('./src/components/frontend/ArticleBox.vue')['default']
    ArticleInfoSide: typeof import('./src/components/frontend/Side/ArticleInfoSide.vue')['default']
    ArticleTable: typeof import('./src/components/backend/Table/ArticleTable.vue')['default']
    Banner: typeof import('./src/components/frontend/Banner.vue')['default']
    CategoryTable: typeof import('./src/components/backend/Table/CategoryTable.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./src/components/frontend/Footer.vue')['default']
    Header: typeof import('./src/components/frontend/Header.vue')['default']
    HomeSide: typeof import('./src/components/frontend/Side/HomeSide.vue')['default']
    Icon: typeof import('./src/components/Child/Icon.vue')['default']
    Pagination: typeof import('./src/components/frontend/Pagination.vue')['default']
    Pet: typeof import('./src/components/frontend/Pet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableDialog: typeof import('./src/components/backend/Table/TableDialog.vue')['default']
    TagTable: typeof import('./src/components/backend/Table/TagTable.vue')['default']
    TotalItem: typeof import('./src/components/backend/DashBoard/TotalItem.vue')['default']
    VisitChart: typeof import('./src/components/backend/DashBoard/VisitChart.vue')['default']
    VisitTable: typeof import('./src/components/backend/DashBoard/VisitTable.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
