server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name:
      blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:30306/dh_blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 8
      # 连接最大存活时间
      max-lifetime: 120
      # 连接在连接池中 最大的空闲时间 idle-timeout 要小于 max-lifetime
      idle-timeout: 110
  servlet:
    multipart:
      max-file-size: 10MB
  web:
    resources:
      static-locations:
        - classpath:/static/
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

# 在这里写博客上传文件的目录
upload:
  path: P:\\Code\\Github\\DH-Blog\\admin\\src\\main\\resources\\static\\articleUpload\\

debug: true
