server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: prod
  application:
    name:
      DH-Blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATASOURCE_HOST}/dh_blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: ${DATASOURCE_USER:root}
    password: ${DATASOURCE_PASSWORD:root}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 8
      # 连接最大存活时间
      max-lifetime: 120
      # 连接在连接池中 最大的空闲时间 idle-timeout 要小于 max-lifetime
      idle-timeout: 110
  servlet:
    multipart:
      max-file-size: 10MB
  web:
    resources:
      static-locations:
        - classpath:/static/
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWD:}
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

qiniu:
  accessKey: ${qiniu.accessKey}
  secretKey: ${qiniu.secretKey}
  bucket: dh-blog
  default-image-name: defaultArticleImg

# 在这里写博客上传文件的目录
upload:
  path: ${UPLOAD_PATH:P:\\Code\\Github\\DH-Blog\\admin\\src\\main\\resources\\static\\articleUpload\\}

debug: false
