/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminFooter: typeof import('./src/components/backend/AdminFooter.vue')['default']
    AdminSide: typeof import('./src/components/backend/AdminSide.vue')['default']
    ArticleBox: typeof import('./src/components/frontend/ArticleBox.vue')['default']
    ArticleInfoSide: typeof import('./src/components/frontend/Side/ArticleInfoSide.vue')['default']
    ArticlePreview: typeof import('./src/components/backend/ArticlePreview.vue')['default']
    ArticleTable: typeof import('./src/components/backend/Table/ArticleTable.vue')['default']
    Banner: typeof import('./src/components/frontend/Banner.vue')['default']
    CategoryTable: typeof import('./src/components/backend/Table/CategoryTable.vue')['default']
    Comment: typeof import('./src/components/frontend/Comment.vue')['default']
    CommentItem: typeof import('./src/components/frontend/Comment/CommentItem.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Footer: typeof import('./src/components/frontend/Footer.vue')['default']
    Header: typeof import('./src/components/frontend/Header.vue')['default']
    HomeSide: typeof import('./src/components/frontend/Side/HomeSide.vue')['default']
    Icon: typeof import('./src/components/Child/Icon.vue')['default']
    Loading: typeof import('./src/components/frontend/Loading.vue')['default']
    Pagination: typeof import('./src/components/frontend/Pagination.vue')['default']
    Pet: typeof import('./src/components/frontend/Pet.vue')['default']
    Publish: typeof import('./src/components/frontend/Comment/Publish.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableDialog: typeof import('./src/components/backend/Table/TableDialog.vue')['default']
    TagTable: typeof import('./src/components/backend/Table/TagTable.vue')['default']
    TotalItem: typeof import('./src/components/backend/DashBoard/TotalItem.vue')['default']
    View: typeof import('./src/components/frontend/Comment/View.vue')['default']
    VisitChart: typeof import('./src/components/backend/DashBoard/VisitChart.vue')['default']
    VisitTable: typeof import('./src/components/backend/DashBoard/VisitTable.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
